select ("subs"."provone" || "subs"."provtwo" ||"subs"."provthree" || "subs"."provfour" || "subs"."provfive" || "subs"."provsix") as provs
from (
SELECT "orderby"."tuid" AS "tuid",
       "subquery7"."nation" AS "nation",
       "subquery7"."o_year" AS "o_year",
       "subquery7"."sum_profit" AS "sum_profit",
       "subquery7"."provone" AS "provone",
       "subquery7"."provtwo" AS "provtwo",
       "subquery7"."provthree" AS "provthree",
       "subquery7"."provfour" AS "provfour",
       "subquery7"."provfive" AS "provfive",
       "subquery7"."provsix" AS "provsix"
FROM (SELECT "group"."tuid" AS "tuid",
             concat_agg("subquery6"."nation") AS "nation",
             concat_agg("subquery6"."o_year") AS "o_year",
             concat_agg("subquery6"."amount") AS "sum_profit",
              array_agg("subquery6"."provone") AS "provone",
              array_agg("subquery6"."provtwo") AS "provtwo",
              array_agg("subquery6"."provthree") AS "provthree",
              array_agg("subquery6"."provfour") AS "provfour",
              array_agg("subquery6"."provfive") AS "provfive",
              array_agg("subquery6"."provsix") AS "provsix"

      FROM (SELECT "join"."tuid" AS "tuid",
                   "RTE5"."n_name" AS "nation",
                   "RTE4"."o_orderdate" AS "o_year",
                   (("RTE2"."l_extendedprice") || ((ARRAY[] :: int4[]) ||
                                                   ("RTE2"."l_discount"))) ||
                   (("RTE3"."ps_supplycost") ||
                    ("RTE2"."l_quantity")) AS "amount",
              "RTE0"."tuid" AS "provone",
              "RTE1"."tuid" AS "provtwo",
              "RTE2"."tuid" AS "provthree",
              "RTE3"."tuid" AS "provfour",
              "RTE4"."tuid" AS "provfive",
              "RTE5"."tuid" AS "provsix"
            FROM part_2 AS "RTE0"("tuid",
                                  "p_partkey",
                                  "p_name",
                                  "p_mfgr",
                                  "p_brand",
                                  "p_type",
                                  "p_size",
                                  "p_container",
                                  "p_retailprice",
                                  "p_comment"),
                 supplier_2 AS "RTE1"("tuid",
                                      "s_suppkey",
                                      "s_name",
                                      "s_address",
                                      "s_nationkey",
                                      "s_phone",
                                      "s_acctbal",
                                      "s_comment"),
                 lineitem_2 AS "RTE2"("tuid",
                                      "l_orderkey",
                                      "l_partkey",
                                      "l_suppkey",
                                      "l_linenumber",
                                      "l_quantity",
                                      "l_extendedprice",
                                      "l_discount",
                                      "l_tax",
                                      "l_returnflag",
                                      "l_linestatus",
                                      "l_shipdate",
                                      "l_commitdate",
                                      "l_receiptdate",
                                      "l_shipinstruct",
                                      "l_shipmode",
                                      "l_comment"),
                 partsupp_2 AS "RTE3"("tuid",
                                      "ps_partkey",
                                      "ps_suppkey",
                                      "ps_availqty",
                                      "ps_supplycost",
                                      "ps_comment"),
                 orders_2 AS "RTE4"("tuid",
                                    "o_orderkey",
                                    "o_custkey",
                                    "o_orderstatus",
                                    "o_totalprice",
                                    "o_orderdate",
                                    "o_orderpriority",
                                    "o_clerk",
                                    "o_shippriority",
                                    "o_comment"),
                 nation_2 AS "RTE5"("tuid",
                                    "n_nationkey",
                                    "n_name",
                                    "n_regionkey",
                                    "n_comment"),
                 LATERAL readjoin(1,
                                  "RTE0"."tuid",
                                  "RTE1"."tuid",
                                  "RTE2"."tuid",
                                  "RTE3"."tuid",
                                  "RTE4"."tuid",
                                  "RTE5"."tuid") AS "join"("tuid")) AS "subquery6"("tuid",
                                                                                   "nation",
                                                                                   "o_year",
                                                                                   "amount"),
           LATERAL readaggregation(2,
                                   "subquery6"."tuid") AS "group"("tuid")
      GROUP BY ("group"."tuid")) AS "subquery7"("tuid",
                                                "nation",
                                                "o_year",
                                                "sum_profit"),
     LATERAL readorderby(4,
                         "subquery7"."tuid") AS "orderby"("tuid")
) subs;