select ("subs"."provone" || "subs"."provtwo" || "subs"."provthree") as provs
from (
SELECT "orderby"."tuid" AS "tuid",
       "subquery8"."ps_partkey" AS "ps_partkey",
       "subquery8"."value" AS "value",
       "subquery8"."provone" AS "provone",
       "subquery8"."provtwo" AS "provtwo",
       "subquery8"."provthree" AS "provthree"

FROM (SELECT "group"."tuid" AS "tuid",
             concat_agg("subquery3"."ps_partkey") AS "ps_partkey",
             concat_agg(("subquery3"."ps_supplycost") ||
                        ("subquery3"."ps_availqty")) AS "value",
              array_agg("subquery3"."provone") AS "provone",
              array_agg("subquery3"."provtwo") AS "provtwo",
              array_agg("subquery3"."provthree") AS "provthree"
      FROM (SELECT "join"."tuid" AS "tuid",
                   "RTE0"."ps_partkey" AS "ps_partkey",
                   "RTE0"."ps_supplycost" AS "ps_supplycost",
                   "RTE0"."ps_availqty" AS "ps_availqty",
                   "RTE0"."tuid" AS "provone",
                   "RTE1"."tuid" AS "provtwo",
                   "RTE2"."tuid" AS "provthree"
            FROM partsupp_2 AS "RTE0"("tuid",
                                      "ps_partkey",
                                      "ps_suppkey",
                                      "ps_availqty",
                                      "ps_supplycost",
                                      "ps_comment"),
                 supplier_2 AS "RTE1"("tuid",
                                      "s_suppkey",
                                      "s_name",
                                      "s_address",
                                      "s_nationkey",
                                      "s_phone",
                                      "s_acctbal",
                                      "s_comment"),
                 nation_2 AS "RTE2"("tuid",
                                    "n_nationkey",
                                    "n_name",
                                    "n_regionkey",
                                    "n_comment"),
                 LATERAL readjoin(1,
                                  "RTE0"."tuid",
                                  "RTE1"."tuid",
                                  "RTE2"."tuid") AS "join"("tuid")) AS "subquery3"("tuid",
                                                                                   "ps_partkey",
                                                                                   "ps_supplycost",
                                                                                   "ps_availqty"),
           LATERAL readaggregation(5,
                                   "subquery3"."tuid") AS "group"("tuid")
      GROUP BY ("group"."tuid")) AS "subquery8"("tuid",
                                                "ps_partkey",
                                                "value"),
     LATERAL readorderby(7,
                         "subquery8"."tuid") AS "orderby"("tuid")
) subs;
